### ISSUE TITLE
Neuromere00030.obj materials file seems to be missing

### ISSUE THREAD

**Issue by jefferis** [Robbie1977/DrosAdultTAGdomains#2]
Neuromere00030.obj.mtl is mentioned but not in repo

**Comment by Robbie1977** [comment]
Was just a default meshlab white:
#
# Wavefront material file
# Converted by Meshlab Group
#

newmtl material_0
Ka 0.200000 0.200000 0.200000
Kd 0.000000 0.000000 0.000000
Ks 1.000000 1.000000 1.000000
Tr 0.000000
illum 2
Ns 0.000000

I'm still testing out the meshes for optimisation of faces will ensure I keep the materials files next change.
